package com.iot.api.model.user;

import static com.iot.api.model.user.AppRoleConstants.*;

public enum AppRole {

    ROLE_ROLEGROUP_ADD(ROLEGROUP_ADD),
    ROLE_ROLEGROUP_UPDATE(ROLEGROUP_UPDATE),
    ROLE_ROLEGROUP_DELETE(ROLEGROUP_DELETE),
    ROLE_ROLEGROUP_READ(ROLEGROUP_READ),

    ROLE_SCHEDULE_READ(SCHEDULE_READ),
    ROLE_SCHEDULE_UPDATE(SCHEDULE_UPDATE),
//    ROLE_SELFROLE_READ(AppRoleConstants.SELFROLE_READ),

    ROLE_VENDOR_ADD(VENDOR_ADD),
    ROLE_VENDOR_READ(VENDOR_READ),
    ROLE_VENDOR_UPDATE(VENDOR_UPDATE),
    ROLE_VENDOR_DELETE(VENDOR_DELETE),

    ROLE_COMPANY_ADD(COMPANY_ADD),
    ROLE_COMPANY_READ(COMPANY_READ),
    ROLE_COMPANY_UPDATE(COMPANY_UPDATE),
    ROLE_COMPANY_DELETE(COMPANY_DELETE),

    ROLE_DEALER_ADD(DEALER_ADD),
    ROLE_DEALER_READ(DEALER_READ),
    ROLE_DEALER_UPDATE(DEALER_UPDATE),
    ROLE_DEALER_DELETE(DEALER_DELETE),

    ROLE_DEALER_GROUP_ADD(DEALER_GROUP_ADD),
    ROLE_DEALER_GROUP_READ(DEALER_GROUP_READ),
    ROLE_DEALER_GROUP_UPDATE(DEALER_GROUP_UPDATE),
    ROLE_DEALER_GROUP_DELETE(DEALER_GROUP_DELETE),

    ROLE_ADDRESS_ADD(ADDRESS_ADD),
    ROLE_ADDRESS_READ(ADDRESS_READ),
    ROLE_ADDRESS_UPDATE(ADDRESS_UPDATE),
    ROLE_ADDRESS_DELETE(ADDRESS_DELETE),

    ROLE_ADDRESS_CONTACT_PERSON_ADD(ADDRESS_CONTACT_PERSON_ADD),
    ROLE_ADDRESS_CONTACT_PERSON_READ(ADDRESS_CONTACT_PERSON_READ),
    ROLE_ADDRESS_CONTACT_PERSON_UPDATE(ADDRESS_CONTACT_PERSON_UPDATE),
    ROLE_ADDRESS_CONTACT_PERSON_DELETE(ADDRESS_CONTACT_PERSON_DELETE),

    ROLE_PRODUCT_USER_ADD(PRODUCT_USER_ADD),
    ROLE_PRODUCT_USER_UPDATE(PRODUCT_USER_UPDATE),
    ROLE_PRODUCT_USER_DELETE(PRODUCT_USER_DELETE),
    ROLE_PRODUCT_USER_READ(PRODUCT_USER_READ),
    ROLE_ALL_USER_READ(ALL_USER_READ),
    ROLE_USER_APPROVE(USER_APPROVE),

    ROLE_COMPANY_USER_ADD(COMPANY_USER_ADD),
    ROLE_COMPANY_USER_UPDATE(COMPANY_USER_UPDATE),
    ROLE_COMPANY_USER_DELETE(COMPANY_USER_DELETE),
    ROLE_COMPANY_USER_READ(COMPANY_USER_READ),

    ROLE_CITY_ADD(CITY_ADD),
    ROLE_CITY_READ(CITY_READ),
    ROLE_CITY_DELETE(CITY_DELETE),
    ROLE_CITY_UPDATE(CITY_UPDATE),

    ROLE_CUSTOMER_ADD(CUSTOMER_ADD),
    ROLE_CUSTOMER_READ(CUSTOMER_READ),
    ROLE_CUSTOMER_DELETE(CUSTOMER_DELETE),
    ROLE_CUSTOMER_UPDATE(CUSTOMER_UPDATE),

    ROLE_SERVICE_ADD(SERVICE_ADD),
    ROLE_SERVICE_READ(SERVICE_READ),
    ROLE_SERVICE_DELETE(SERVICE_DELETE),
    ROLE_SERVICE_UPDATE(SERVICE_UPDATE),

    ROLE_BRAND_ADD(BRAND_ADD),
    ROLE_BRAND_READ(BRAND_READ),
    ROLE_BRAND_UPDATE(BRAND_UPDATE),
    ROLE_BRAND_DELETE(BRAND_DELETE),

    ROLE_AUDIT_ADD(AUDIT_ADD),
    ROLE_AUDIT_READ(AUDIT_READ),
    ROLE_AUDIT_MOBILE_READ(AUDIT_MOBILE_READ),
    ROLE_AUDIT_UPDATE(AUDIT_UPDATE),
    ROLE_AUDIT_STATUS_UPDATE(AUDIT_STATUS_UPDATE),
    ROLE_AUDIT_ASSIGN_AUDITOR(AUDIT_ASSIGN_AUDITOR),
    ROLE_AUDIT_DELETE(AUDIT_DELETE),

    ROLE_AUDIT_REPORT_READ(AUDIT_REPORT_READ),

    ROLE_STOCKDATA_ADD(STOCKDATA_ADD),
    ROLE_STOCKDATA_READ(STOCKDATA_READ),
    ROLE_STOCKDATA_UPDATE(STOCKDATA_UPDATE),
    ROLE_STOCKDATA_DELETE(STOCKDATA_DELETE),

    ROLE_USER_PROFILE_ADD(USER_PROFILE_ADD),
    ROLE_USER_PROFILE_UPDATE(USER_PROFILE_UPDATE),

    ROLE_VENDOR_USER_ADD(VENDOR_USER_ADD),
    ROLE_VENDOR_USER_UPDATE(VENDOR_USER_UPDATE),
    ROLE_VENDOR_USER_DELETE(VENDOR_USER_DELETE),
    ROLE_VENDOR_USER_READ(VENDOR_USER_READ);


    private String stringValue;

    AppRole(String productUserAdd) {

    }

    void Strings(final String s) {
        stringValue = s;
    }

    public String toString() {
        return stringValue;
    }
}
